'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RevenuQuebec.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;compagnie&gt;
        '''		&lt;nom&gt;Entretien PKP Manoir&lt;/nom&gt;
        '''		&lt;revenu&gt;450000&lt;/revenu&gt;
        '''		&lt;personne id=&quot;000002&quot; nom=&quot;Le chien de Pierre-Karl&quot;/&gt;
        '''		&lt;personne id=&quot;000003&quot; nom=&quot;Le jardinier de Pierre-Karl&quot;/&gt;
        '''		&lt;compagnie&gt;
        '''			&lt;nom&gt;Entretien PKP Maison&lt;/nom&gt;
        '''			&lt;revenu&gt;45000&lt;/revenu&gt;
        '''			&lt;personne id=&quot;000004&quot; nom=&quot;Le cuisinier de Pierre-Karl&quot;/&gt;
        '''			&lt;compagnie&gt;
        '''				&lt;nom&gt;Entretien PKP Bécosse&lt;/nom&gt;
        '''				&lt;revenu&gt;4500&lt;/revenu&gt;
        '''				&lt;personne id=&quot;000005&quot; nom=&quot;Le concierge de Pierre-Karl&quot;/&gt;
        '''				&lt;compagnie&gt;
        '''					&lt;nom&gt;Entretie [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property entretien_pkp() As String
            Get
                Return ResourceManager.GetString("entretien_pkp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property open_file_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open_file-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;compagnie&gt;
        '''	&lt;nom&gt;Québécor Média&lt;/nom&gt;
        '''	&lt;revenu&gt;450000000&lt;/revenu&gt;
        '''	&lt;personne id=&quot;000001&quot; nom=&quot;Pierre-Karl Péladeau&quot;/&gt;
        '''	&lt;compagnie&gt;
        '''		&lt;nom&gt;Vidéotron&lt;/nom&gt;
        '''		&lt;revenu&gt;45000000&lt;/revenu&gt;
        '''		&lt;personne id=&quot;000002&quot; nom=&quot;Le chien de Pierre-Karl&quot;/&gt;
        '''		&lt;personne id=&quot;000003&quot; nom=&quot;Le jardinier de Pierre-Karl&quot;/&gt;
        '''		&lt;personne id=&quot;000004&quot; nom=&quot;Le cuisinier de Pierre-Karl&quot;/&gt;
        '''	&lt;/compagnie&gt;
        '''&lt;/compagnie&gt;
        '''&lt;compagnie&gt;
        '''	&lt;nom&gt;Bebelle Canada&lt;/nom&gt;
        '''	&lt;revenu&gt;450000000&lt;/revenu&gt;
        '''	&lt;personne id=&quot;000008&quot; nom=&quot;Mr Bell&quot;/&gt;
        '''&lt;/co [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property quebecor() As String
            Get
                Return ResourceManager.GetString("quebecor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rq() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rq", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rq1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rq1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;compagnie&gt;
        '''	&lt;nom&gt;Vidéotron&lt;/nom&gt;
        '''	&lt;revenu&gt;45000000&lt;/revenu&gt;
        '''	&lt;personne id=&quot;000002&quot; nom=&quot;Le chien de Pierre-Karl&quot;/&gt;
        '''	&lt;personne id=&quot;000003&quot; nom=&quot;Le jardinier de Pierre-Karl&quot;/&gt;
        '''	&lt;personne id=&quot;000004&quot; nom=&quot;Le cuisinier de Pierre-Karl&quot;/&gt;
        '''	&lt;personne id=&quot;000001&quot; nom=&quot;Pierre-Karl Péladeau&quot;/&gt;
        '''	&lt;compagnie&gt;
        '''		&lt;nom&gt;Vidéotron mobile&lt;/nom&gt;
        '''		&lt;revenu&gt;4500000&lt;/revenu&gt;
        '''		&lt;personne id=&quot;000007&quot; nom=&quot;Le voisin de Pierre-Karl&quot;/&gt;
        '''	&lt;/compagnie&gt;
        '''&lt;/compagnie&gt;
        '''.
        '''</summary>
        Friend ReadOnly Property videotron() As String
            Get
                Return ResourceManager.GetString("videotron", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
